
CREATE TABLE HD_USER (
	USER_ID INTEGER NOT NULL,
	LOGIN VARCHAR(96) NOT NULL,
	PASSW VARCHAR(32) NOT NULL,
	FIRST_NAME VARCHAR(64),
	LAST_NAME VARCHAR(128),
	EMAIL VARCHAR(128) NOT NULL,
	PHONE VARCHAR(30),
	MOBILE VARCHAR(20),
	ROLE SMALLINT NOT NULL,
	IS_ACTIVE BOOLEAN,
	CONSTRAINT HD_USER_PK PRIMARY KEY( USER_ID )
);

ALTER TABLE HD_USER ALTER COLUMN ROLE SET DEFAULT 0;

CREATE TRIGGER TR_HD_USER_BI FOR HD_USER
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
	IF( NEW.user_id IS NULL ) THEN 
		NEW.user_id = GEN_ID( GEN_HD_USER_ID, 1 );
END
;

CREATE GENERATOR GEN_HD_USER_ID;
SET GENERATOR GEN_HD_USER_ID TO 0;

